services:
  postgres:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: domainguard
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '${PG_ADMIN_PORT:-5050}:80'
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:80']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.9-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_HOSTS: 'redis'
    depends_on:
      - redis
    ports:
      - '${REDIS_COMMANDER_PORT:-8081}:8081'
    healthcheck:
      test: ['CMD', '/redis-commander/bin/healthcheck.js']
      interval: 10s
      timeout: 5s
      retries: 5
